version: 2

before:
  hooks:
    - go install github.com/tc-hib/go-winres@v0.3.3
    - go-winres make --in winres/winres.json --out cmd/quil/rsrc --product-version {{ .Version }} --file-version {{ .Version }}
    - go-winres make --in winres/winres.json --out cmd/quild/rsrc --product-version {{ .Version }} --file-version {{ .Version }}
    - go mod tidy -diff
    - go vet ./...

builds:
  - id: quil
    main: ./cmd/quil
    binary: quil
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: quild
    main: ./cmd/quild
    binary: quild
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    ids:
      - quil
      - quild
    name_template: "quil_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  disable: true

release:
  github:
    owner: artyomsv
    name: quil
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
