// Package claudehook manages Claude Code's SessionStart hook for Quil.
//
// Quil tracks Claude session-id rotation (/clear, compaction, /resume) by
// registering a SessionStart hook via --settings (inline JSON) when it
// spawns a claude-code pane. The hook script lives under $QUIL_HOME/claudehook/
// and writes per-pane session ids to $QUIL_HOME/sessions/<paneID>.id.
//
// This package never reads or writes ~/.claude/settings.json — the hook is
// per-invocation, lives entirely under QuilDir, and no user Claude config is
// mutated.
package claudehook

import (
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

//go:embed scripts/*
var scripts embed.FS

const (
	unixScriptName    = "quil-session-hook.sh"
	windowsScriptName = "quil-session-hook.ps1"
)

// shellUnsafeChars are characters that, if present in $QUIL_HOME, would let an
// attacker break out of the quoted hook-command string we hand to Claude. We
// refuse to install the hook in that case rather than try to escape every
// shell variant Claude might use to run it.
const shellUnsafeChars = "\"`$\n\r\t"

// ValidateQuilDir reports an error if quilDir contains characters that cannot
// be safely embedded in the hook command string. Used by EnsureScripts so the
// daemon can decide at startup whether to register the hook at all.
func ValidateQuilDir(quilDir string) error {
	if quilDir == "" {
		return errors.New("claudehook: empty quilDir")
	}
	if strings.ContainsAny(quilDir, shellUnsafeChars) {
		return fmt.Errorf("claudehook: quilDir %q contains shell-unsafe characters", quilDir)
	}
	return nil
}

// validatePaneID rejects pane ids that could let a caller escape the sessions
// directory. Defense-in-depth: today every caller routes through pane IDs
// generated by uuid + an isValidHexID guard, but the package keeps its own
// invariant so a future caller cannot accidentally read arbitrary files.
func validatePaneID(paneID string) error {
	if paneID == "" {
		return errors.New("claudehook: empty paneID")
	}
	if strings.ContainsAny(paneID, `/\`) || strings.Contains(paneID, "..") {
		return fmt.Errorf("claudehook: paneID %q contains path separators or parent traversal", paneID)
	}
	return nil
}

// EnsureScripts writes the embedded SessionStart hook scripts to
// $quilDir/claudehook/. Each script is written via a temp file + rename so a
// hook firing concurrently with the rewrite never sees a truncated file.
// Mirrors shellinit.EnsureInitDir.
func EnsureScripts(quilDir string) error {
	if err := ValidateQuilDir(quilDir); err != nil {
		return err
	}
	dir := filepath.Join(quilDir, "claudehook")
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("create claudehook dir: %w", err)
	}
	files := map[string]string{
		filepath.Join(dir, unixScriptName):    "scripts/" + unixScriptName,
		filepath.Join(dir, windowsScriptName): "scripts/" + windowsScriptName,
	}
	for dst, src := range files {
		data, err := scripts.ReadFile(src)
		if err != nil {
			return fmt.Errorf("read embedded %s: %w", src, err)
		}
		if err := atomicWrite(dst, data, 0700); err != nil {
			return fmt.Errorf("write %s: %w", dst, err)
		}
	}
	return nil
}

// atomicWrite writes data to path via a temp file in the same directory and a
// rename. Removes the temp on any error so we never leak a half-written file.
func atomicWrite(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".tmp.*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	cleanup := func() { os.Remove(tmpPath) }
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		cleanup()
		return err
	}
	if err := tmp.Chmod(perm); err != nil {
		tmp.Close()
		cleanup()
		return err
	}
	if err := tmp.Close(); err != nil {
		cleanup()
		return err
	}
	if err := os.Rename(tmpPath, path); err != nil {
		cleanup()
		return err
	}
	return nil
}

// ScriptPath returns the absolute path to the hook script for the current
// platform. The file must have been written by EnsureScripts first.
func ScriptPath(quilDir string) string {
	name := unixScriptName
	if runtime.GOOS == "windows" {
		name = windowsScriptName
	}
	return filepath.Join(quilDir, "claudehook", name)
}

// HookCommand returns the shell command Claude should execute for the
// SessionStart hook. EnsureScripts must have validated quilDir first; the
// returned string is safe to embed in a JSON `command` field that Claude will
// later shell-execute.
func HookCommand(quilDir string) string {
	p := ScriptPath(quilDir)
	if runtime.GOOS == "windows" {
		return fmt.Sprintf(`powershell -NoProfile -ExecutionPolicy Bypass -File "%s"`, p)
	}
	return fmt.Sprintf(`sh "%s"`, p)
}

// settingsSchema mirrors the subset of Claude Code's settings.json format
// we need to register a SessionStart hook. Only SessionStart is populated.
type settingsSchema struct {
	Hooks map[string][]hookMatcher `json:"hooks"`
}

type hookMatcher struct {
	Hooks []hookEntry `json:"hooks"`
}

type hookEntry struct {
	Type    string `json:"type"`
	Command string `json:"command"`
}

// BuildSettingsJSON returns the inline JSON string Quil passes to
// `claude --settings <json>`. The returned payload registers a single
// SessionStart hook whose command is `cmd`.
func BuildSettingsJSON(cmd string) (string, error) {
	s := settingsSchema{
		Hooks: map[string][]hookMatcher{
			"SessionStart": {{
				Hooks: []hookEntry{{Type: "command", Command: cmd}},
			}},
		},
	}
	b, err := json.Marshal(s)
	if err != nil {
		return "", fmt.Errorf("marshal claude settings: %w", err)
	}
	return string(b), nil
}

// sessionIDFile returns the absolute path to <paneID>.id.
func sessionIDFile(quilDir, paneID string) string {
	return filepath.Join(quilDir, "sessions", paneID+".id")
}

// ReadPersistedSessionID returns the session id the SessionStart hook last
// wrote for the given pane. A missing file is reported via the returned
// error satisfying errors.Is(err, os.ErrNotExist) so callers can cleanly
// distinguish "no hook fired yet" from a corrupted file.
//
// Reads the file via a single open file descriptor + Stat so the reported
// modTime always corresponds to the bytes returned, even if the hook rotates
// the file between calls.
func ReadPersistedSessionID(quilDir, paneID string) (id string, modTime time.Time, err error) {
	if quilDir == "" {
		return "", time.Time{}, errors.New("claudehook: empty quilDir")
	}
	if err := validatePaneID(paneID); err != nil {
		return "", time.Time{}, err
	}
	f, err := os.Open(sessionIDFile(quilDir, paneID))
	if err != nil {
		return "", time.Time{}, err
	}
	defer f.Close()
	info, err := f.Stat()
	if err != nil {
		return "", time.Time{}, err
	}
	// Hook writes a single uuid line; cap the read to keep a malformed file
	// from forcing us to read megabytes.
	const maxIDBytes = 256
	buf, err := io.ReadAll(io.LimitReader(f, maxIDBytes))
	if err != nil {
		return "", info.ModTime(), err
	}
	return strings.TrimSpace(string(buf)), info.ModTime(), nil
}
