// Package claudehook manages Claude Code's multi-event hook for Quil.
//
// Quil tracks Claude session-id rotation (/clear, compaction, /resume) and
// forwards Claude's lifecycle/notification hooks by registering a hook command
// via --settings (inline JSON) when it spawns a claude-code pane. The hook
// command invokes the quil daemon binary's `claude-hook` subcommand (see
// runhook.go + cmd/quild), which reads the hook JSON on stdin and writes the
// per-pane session id to $QUIL_HOME/sessions/<paneID>.id and/or appends a
// hookevents JSONL line to $QUIL_HOME/events/<paneID>.jsonl.
//
// Invoking the native binary instead of a per-event shell script eliminates
// the dominant hook latency (PowerShell 5.1 cold start was ~1-4 s) and the
// hand-rolled JSON escaping the shell producers required.
//
// This package never reads or writes ~/.claude/settings.json — the hook is
// per-invocation, lives entirely under QuilDir, and no user Claude config is
// mutated.
package claudehook

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// validatePaneID rejects pane ids that could let a caller escape the sessions
// directory. Defense-in-depth: today every caller routes through pane IDs
// generated by uuid + an isValidHexID guard, but the package keeps its own
// invariant so a future caller cannot accidentally read arbitrary files.
func validatePaneID(paneID string) error {
	if paneID == "" {
		return errors.New("claudehook: empty paneID")
	}
	if strings.ContainsAny(paneID, `/\`) || strings.Contains(paneID, "..") {
		return fmt.Errorf("claudehook: paneID %q contains path separators or parent traversal", paneID)
	}
	// Reject control characters (incl. newline) so a hostile pane id cannot
	// forge log lines when reflected into the hook log, nor smuggle a NUL that
	// truncates a path on some platforms. %q in the error escapes them safely.
	for _, r := range paneID {
		if r < 0x20 || r == 0x7f {
			return fmt.Errorf("claudehook: paneID %q contains a control character", paneID)
		}
	}
	return nil
}

// atomicWrite writes data to path via a temp file in the same directory and a
// rename. Removes the temp on any error so we never leak a half-written file.
func atomicWrite(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".tmp.*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	// cleanup removes the half-written temp on any error. The Remove return
	// value is intentionally discarded: we are already returning an error to
	// the caller, and the dir is 0700 so a leaked temp is owner-only.
	cleanup := func() { _ = os.Remove(tmpPath) }
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		cleanup()
		return err
	}
	if err := tmp.Chmod(perm); err != nil {
		tmp.Close()
		cleanup()
		return err
	}
	if err := tmp.Close(); err != nil {
		cleanup()
		return err
	}
	if err := os.Rename(tmpPath, path); err != nil {
		cleanup()
		return err
	}
	return nil
}

// HookCommand returns the command Claude runs for each registered hook event.
// It invokes the running quil daemon binary's `claude-hook` subcommand, which
// reads the hook JSON on stdin and writes the session-id file / spool line
// natively. exePath must be the absolute path to the quild binary (the daemon
// passes os.Executable()); it is double-quoted so paths with spaces work under
// the shell Claude uses to run hook commands. The command is embedded in the
// --settings JSON via BuildSettingsJSON, which JSON-escapes it.
//
// exePath is the daemon's own binary location — OS-controlled, never user
// input — so a shell-metacharacter break-out is not a realistic concern; a `"`
// is illegal in a Windows path and effectively never appears on Unix.
func HookCommand(exePath string) string {
	return fmt.Sprintf(`"%s" claude-hook`, exePath)
}

// settingsSchema mirrors the subset of Claude Code's settings.json format
// we need to register hooks. Only the forwarded events are populated.
type settingsSchema struct {
	Hooks map[string][]hookMatcher `json:"hooks"`
}

type hookMatcher struct {
	Hooks []hookEntry `json:"hooks"`
}

type hookEntry struct {
	Type    string `json:"type"`
	Command string `json:"command"`
}

// forwardedHookEvents lists the Claude Code hook events Quil registers in
// the inline --settings JSON. The native claude-hook subcommand branches on
// hook_event_name from stdin so the same command handles every entry.
//
// SessionStart is the original — it writes the session id file used by the
// resume-args path. The rest are the v1 "default" tier from the hook events
// plan: notification + permission + lifecycle. PreToolUse / PostToolUse and
// friends are NOT in this list (too noisy at scale).
var forwardedHookEvents = []string{
	"SessionStart",
	"SessionEnd",
	"UserPromptSubmit",
	"Notification",
	"PermissionRequest",
	"Stop",
	"PreCompact",
	"PostCompact",
	"SubagentStart",
	"SubagentStop",
	"TaskCreated",
	"TaskCompleted",
}

// BuildSettingsJSON returns the inline JSON string Quil passes to
// `claude --settings <json>`. Registers Quil's hook command under every
// entry in forwardedHookEvents — the native subcommand then branches on the
// hook_event_name field of the stdin JSON.
func BuildSettingsJSON(cmd string) (string, error) {
	s := settingsSchema{
		Hooks: make(map[string][]hookMatcher, len(forwardedHookEvents)),
	}
	for _, name := range forwardedHookEvents {
		s.Hooks[name] = []hookMatcher{{
			Hooks: []hookEntry{{Type: "command", Command: cmd}},
		}}
	}
	b, err := json.Marshal(s)
	if err != nil {
		return "", fmt.Errorf("marshal claude settings: %w", err)
	}
	return string(b), nil
}

// sessionIDFile returns the absolute path to <paneID>.id.
func sessionIDFile(quilDir, paneID string) string {
	return filepath.Join(quilDir, "sessions", paneID+".id")
}

// ReadPersistedSessionID returns the session id the SessionStart hook last
// wrote for the given pane. A missing file is reported via the returned
// error satisfying errors.Is(err, os.ErrNotExist) so callers can cleanly
// distinguish "no hook fired yet" from a corrupted file.
//
// Reads the file via a single open file descriptor + Stat so the reported
// modTime always corresponds to the bytes returned, even if the hook rotates
// the file between calls.
func ReadPersistedSessionID(quilDir, paneID string) (id string, modTime time.Time, err error) {
	if quilDir == "" {
		return "", time.Time{}, errors.New("claudehook: empty quilDir")
	}
	if err := validatePaneID(paneID); err != nil {
		return "", time.Time{}, err
	}
	f, err := os.Open(sessionIDFile(quilDir, paneID))
	if err != nil {
		return "", time.Time{}, err
	}
	defer f.Close()
	info, err := f.Stat()
	if err != nil {
		return "", time.Time{}, err
	}
	// Hook writes a single uuid line; cap the read to keep a malformed file
	// from forcing us to read megabytes.
	const maxIDBytes = 256
	buf, err := io.ReadAll(io.LimitReader(f, maxIDBytes))
	if err != nil {
		return "", info.ModTime(), err
	}
	return strings.TrimSpace(string(buf)), info.ModTime(), nil
}
