// Package changelog serves the one-line release highlights the TUI shows after
// an upgrade. The data is a line-oriented file generated by
// scripts/promote-changelog.sh and embedded at build time — deliberately not
// JSON, because a headline is single-line by definition, so newline is the only
// delimiter and the POSIX-sh writer never needs escaping logic.
//
// The binary reading this file is by definition newer than every version it
// must describe, which is what makes embedding sufficient: no network, no
// failure modes, works offline.
//
// There is no epoch marker and nothing is backfilled. The file starts empty and
// only promote() ever writes it, so a version is either present with complete
// data or absent entirely.
package changelog

import (
	"bufio"
	"bytes"
	_ "embed"
	"strings"
	"sync"

	"github.com/artyomsv/quil/internal/version"
)

//go:embed highlights.txt
var highlightsData []byte

// Kind is the section a headline renders under.
type Kind int

const (
	KindAdded Kind = iota
	KindChanged
	KindDeprecated
	KindRemoved
	KindFixed
	KindSecurity
)

// Entry is one headline and the kind of change it describes.
type Entry struct {
	Kind Kind
	Text string
}

// Release is one version's highlights, in the order the promoter wrote them.
type Release struct {
	Version string
	Date    string
	Entries []Entry
}

// Window is the set of releases an upgrade crossed.
type Window struct {
	From string
	To   string
	// Total counts every release in (From, To], including ones that carried no
	// user-facing change. They happened; the header says so.
	Total int
	// Releases holds only those with entries, newest first, deduplicated.
	Releases []Release
}

// kindOf maps a record letter to its Kind. ok is false for any other letter.
func kindOf(c byte) (Kind, bool) {
	switch c {
	case 'A':
		return KindAdded, true
	case 'C':
		return KindChanged, true
	case 'D':
		return KindDeprecated, true
	case 'R':
		return KindRemoved, true
	case 'F':
		return KindFixed, true
	case 'S':
		return KindSecurity, true
	}
	return 0, false
}

// parseHighlights reads the generated file. A malformed line is SKIPPED, never
// fatal: the file is generated and checked in, so a bad line means a generator
// bug, and losing one bullet is a better outcome for the user than a TUI that
// refuses to start.
func parseHighlights(data []byte) []Release {
	var releases []Release
	sc := bufio.NewScanner(bytes.NewReader(data))
	for sc.Scan() {
		line := strings.TrimRight(sc.Text(), "\r")
		if line == "" || line[0] == '#' {
			continue
		}
		if strings.HasPrefix(line, "V ") {
			fields := strings.Fields(line[2:])
			if len(fields) < 2 {
				continue
			}
			releases = append(releases, Release{Version: fields[0], Date: fields[1]})
			continue
		}
		kind, ok := kindOf(line[0])
		if !ok || len(line) < 3 || line[1] != ' ' {
			continue
		}
		if len(releases) == 0 {
			continue // an entry before any V record has no owner
		}
		last := &releases[len(releases)-1]
		last.Entries = append(last.Entries, Entry{Kind: kind, Text: line[2:]})
	}
	return releases
}

type corpus struct{ releases []Release }

// parseEmbedded parses the embedded file once. sync.OnceValue rather than a
// bare sync.Once: nothing here may be copied, because go vet's copylocks check
// runs in CI and a test that swapped a Once by value would fail it.
var parseEmbedded = sync.OnceValue(func() *corpus {
	return &corpus{releases: parseHighlights(highlightsData)}
})

// corpusOverride replaces the embedded corpus. Tests only, via withCorpus.
// Because this is a package-level var, no test in this package may run in
// parallel.
var corpusOverride *corpus

func load() *corpus {
	if corpusOverride != nil {
		return corpusOverride
	}
	return parseEmbedded()
}

// All returns every recorded release, newest first.
func All() []Release { return load().releases }

// Latest returns the most recent recorded release, or nil when the file holds
// none. The F1 path uses it directly rather than deriving a range — on the
// release that ships this feature there is no earlier record, so a derived
// range would come back empty and the menu row would be a silent no-op on
// exactly the version that introduces it.
func Latest() *Release {
	rels := All()
	if len(rels) == 0 {
		return nil
	}
	r := rels[0]
	return &r
}

// Between returns the window for an upgrade from → to. Bounds are compared with
// version.Compare, so the range is exclusive-low and inclusive-high. ok is
// false only when a bound is unparseable; a from at or after to yields an empty
// window with ok=true.
func Between(from, to string) (Window, bool) {
	// version.Parsed returns (major, minor, patch, err) — four values.
	if _, _, _, err := version.Parsed(from); err != nil {
		return Window{}, false
	}
	if _, _, _, err := version.Parsed(to); err != nil {
		return Window{}, false
	}
	w := Window{From: from, To: to}
	seen := make(map[string]bool)
	for _, r := range All() {
		if cmp, err := version.Compare(r.Version, from); err != nil || cmp <= 0 {
			continue
		}
		if cmp, err := version.Compare(r.Version, to); err != nil || cmp > 0 {
			continue
		}
		w.Total++
		// Deduplicate on exact headline text, keeping the newest occurrence.
		// Iteration is newest-first, so the first sighting wins.
		kept := make([]Entry, 0, len(r.Entries))
		for _, e := range r.Entries {
			if seen[e.Text] {
				continue
			}
			seen[e.Text] = true
			kept = append(kept, e)
		}
		if len(kept) > 0 {
			w.Releases = append(w.Releases, Release{Version: r.Version, Date: r.Date, Entries: kept})
		}
	}
	return w, true
}
