package changelog

import (
	"bytes"
	"testing"

	"github.com/artyomsv/quil/internal/version"
)

// No test in this file may call t.Parallel: withCorpus mutates a package-level
// var, and CI has already caught a package-var race between two parallel tests
// in this repo.

const sample = `# generated by scripts/promote-changelog.sh — do not edit
V 1.52.0 2026-03-03
A Worktree panes open from the tab menu
F Paste no longer drops the first character
V 1.51.0 2026-02-02
C F1 → Shortcuts is derived from your keymap
D The json_transform action is going away
R The legacy pane migration prompt is gone
S Tokens are no longer written to the MCP log
V 1.50.0 2026-01-01
V 1.49.0 2025-12-01
A An older feature
`

func TestParseHighlights_ReadsReleasesNewestFirst(t *testing.T) {
	rels := parseHighlights([]byte(sample))
	if len(rels) != 4 {
		t.Fatalf("got %d releases, want 4", len(rels))
	}
	if rels[0].Version != "1.52.0" || rels[0].Date != "2026-03-03" {
		t.Errorf("first release = %q %q, want 1.52.0 2026-03-03", rels[0].Version, rels[0].Date)
	}
	if rels[3].Version != "1.49.0" {
		t.Errorf("last release = %q, want 1.49.0", rels[3].Version)
	}
	if len(rels[0].Entries) != 2 {
		t.Fatalf("1.52.0 has %d entries, want 2", len(rels[0].Entries))
	}
	if rels[0].Entries[0].Kind != KindAdded ||
		rels[0].Entries[0].Text != "Worktree panes open from the tab menu" {
		t.Errorf("entry 0 = %v %q", rels[0].Entries[0].Kind, rels[0].Entries[0].Text)
	}
	if len(rels[2].Entries) != 0 {
		t.Errorf("1.50.0 has %d entries, want 0", len(rels[2].Entries))
	}
}

func TestParseHighlights_AllKindLetters(t *testing.T) {
	rels := parseHighlights([]byte(sample))
	want := []Kind{KindChanged, KindDeprecated, KindRemoved, KindSecurity}
	got := rels[1].Entries
	if len(got) != len(want) {
		t.Fatalf("1.51.0 has %d entries, want %d", len(got), len(want))
	}
	for i := range want {
		if got[i].Kind != want[i] {
			t.Errorf("entry %d kind = %v, want %v", i, got[i].Kind, want[i])
		}
	}
}

func TestParseHighlights_SkipsMalformedLinesWithoutFailing(t *testing.T) {
	in := `# comment
Z unknown letter
V
V 1.1.0
A orphan before any version
V 1.2.0 2026-01-01
A kept
`
	rels := parseHighlights([]byte(in))
	if len(rels) != 1 {
		t.Fatalf("got %d releases, want 1 (only the well-formed V line)", len(rels))
	}
	if rels[0].Version != "1.2.0" || len(rels[0].Entries) != 1 || rels[0].Entries[0].Text != "kept" {
		t.Errorf("got %+v, want 1.2.0 with one entry %q", rels[0], "kept")
	}
}

func TestParseHighlights_EmptyFile(t *testing.T) {
	if rels := parseHighlights(nil); len(rels) != 0 {
		t.Errorf("got %d releases, want 0", len(rels))
	}
}

func TestBetween_BoundsAreExclusiveLowInclusiveHigh(t *testing.T) {
	withCorpus(t, sample)
	w, ok := Between("1.50.0", "1.52.0")
	if !ok {
		t.Fatal("ok = false, want true")
	}
	if w.Total != 2 {
		t.Errorf("Total = %d, want 2 (1.51.0 and 1.52.0; 1.50.0 is the excluded low bound)", w.Total)
	}
	for _, r := range w.Releases {
		if r.Version == "1.50.0" {
			t.Error("the low bound must be excluded")
		}
	}
	if len(w.Releases) != 2 {
		t.Errorf("got %d releases with entries, want 2", len(w.Releases))
	}
}

func TestBetween_EmptyReleaseIsCountedButNotRendered(t *testing.T) {
	withCorpus(t, sample)
	w, _ := Between("1.49.0", "1.52.0")
	if w.Total != 3 {
		t.Errorf("Total = %d, want 3 (1.50.0 counts even with no entries)", w.Total)
	}
	for _, r := range w.Releases {
		if r.Version == "1.50.0" {
			t.Error("1.50.0 has no entries and must not render as a section")
		}
	}
	if len(w.Releases) != 2 {
		t.Errorf("got %d renderable releases, want 2", len(w.Releases))
	}
}

func TestBetween_DeduplicatesIdenticalHeadlinesKeepingNewest(t *testing.T) {
	withCorpus(t, `V 1.3.0 2026-03-01
F Paste no longer drops the first character
V 1.2.0 2026-02-01
F Paste no longer drops the first character
A Something else
`)
	w, _ := Between("1.1.0", "1.3.0")
	n := 0
	for _, r := range w.Releases {
		for _, e := range r.Entries {
			if e.Text == "Paste no longer drops the first character" {
				n++
			}
		}
	}
	if n != 1 {
		t.Errorf("the repeated headline appears %d times, want 1", n)
	}
	if len(w.Releases) != 2 || w.Releases[0].Version != "1.3.0" {
		t.Errorf("the newest occurrence must be the one kept; got %+v", w.Releases)
	}
}

func TestBetween_FromNewerThanOrEqualToToIsAnEmptyWindow(t *testing.T) {
	withCorpus(t, sample)
	for _, tc := range []struct{ from, to string }{
		{"1.52.0", "1.52.0"},
		{"1.52.0", "1.50.0"},
	} {
		w, ok := Between(tc.from, tc.to)
		if !ok {
			t.Errorf("%s→%s: ok = false, want true", tc.from, tc.to)
		}
		if len(w.Releases) != 0 || w.Total != 0 {
			t.Errorf("%s→%s: want an empty window, got %+v", tc.from, tc.to, w)
		}
	}
}

func TestBetween_UnparseableBoundIsNotOK(t *testing.T) {
	withCorpus(t, sample)
	for _, tc := range []struct{ from, to string }{
		{"dev", "1.52.0"},
		{"1.50.0", ""},
	} {
		if _, ok := Between(tc.from, tc.to); ok {
			t.Errorf("%q→%q: ok = true, want false", tc.from, tc.to)
		}
	}
}

// version.Compare ignores pre-release suffixes, so 1.52.0-rc1 and 1.52.0 are
// the same version. Pinned so the behaviour is deliberate, not discovered.
func TestBetween_PrereleaseToReleaseIsEmpty(t *testing.T) {
	withCorpus(t, sample)
	w, ok := Between("1.52.0-rc1", "1.52.0")
	if !ok {
		t.Fatal("ok = false, want true")
	}
	if len(w.Releases) != 0 {
		t.Errorf("want an empty window, got %+v", w)
	}
}

func TestLatest_ReturnsNewestAndNilOnEmpty(t *testing.T) {
	withCorpus(t, sample)
	if got := Latest(); got == nil || got.Version != "1.52.0" {
		t.Errorf("Latest() = %+v, want 1.52.0", got)
	}
	withCorpus(t, "# nothing here\n")
	if got := Latest(); got != nil {
		t.Errorf("Latest() on an empty corpus = %+v, want nil", got)
	}
}

// Invariants that must hold forever. Not bound to the file's contents, which
// change on every release.
func TestEmbeddedHighlights_IsWellFormedAndNewestFirst(t *testing.T) {
	rels := All()
	for i, r := range rels {
		if _, _, _, err := version.Parsed(r.Version); err != nil {
			t.Errorf("release %d has unparseable version %q", i, r.Version)
		}
		if i == 0 {
			continue
		}
		cmp, err := version.Compare(rels[i-1].Version, r.Version)
		if err != nil {
			t.Fatalf("comparing %q and %q: %v", rels[i-1].Version, r.Version, err)
		}
		if cmp <= 0 {
			t.Errorf("records are not newest-first: %q precedes %q", rels[i-1].Version, r.Version)
		}
	}
}

func TestEmbeddedHighlights_HasNoCarriageReturns(t *testing.T) {
	if bytes.Contains(highlightsData, []byte("\r")) {
		t.Error("highlights.txt contains CR — check .gitattributes eol=lf")
	}
}
